#!/bin/bash
#
# SkillFade - One-Command Shared VPS Deployment
# For VPS that already has another web project running on ports 80/443
#
# Usage: ./scripts/setup-shared-vps.sh
#    or: ./scripts/setup-shared-vps.sh --domain skillfade.website --email you@email.com
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║      SkillFade - Shared VPS Deployment                    ║"
    echo "║   Deploy alongside existing web projects                  ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() { echo -e "\n${CYAN}▶ $1${NC}"; }
print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ $1${NC}"; }
print_error() { echo -e "${RED}✗ $1${NC}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.shared.yml"

# Default values
DOMAIN=""
EMAIL=""
SKIP_SSL=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)   DOMAIN="$2"; shift 2 ;;
        --email)    EMAIL="$2"; shift 2 ;;
        --skip-ssl) SKIP_SSL=true; shift ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --domain DOMAIN   Your domain name (e.g. skillfade.website)"
            echo "  --email EMAIL     Email for SSL certificate"
            echo "  --skip-ssl        Skip SSL certificate setup"
            echo "  -h, --help        Show this help"
            echo ""
            echo "Examples:"
            echo "  $0 --domain skillfade.website --email admin@example.com"
            echo "  $0   # interactive mode, will ask for domain"
            exit 0
            ;;
        *) print_error "Unknown option: $1"; exit 1 ;;
    esac
done

# ─────────────────────────────────────────────────────────────────
# Step 1: Check & Install Docker
# ─────────────────────────────────────────────────────────────────
install_docker() {
    print_step "Checking Docker..."

    if command -v docker &> /dev/null; then
        print_success "Docker already installed"
    else
        print_warning "Docker not found. Installing..."
        curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        sudo sh /tmp/get-docker.sh
        sudo usermod -aG docker "$USER"
        rm /tmp/get-docker.sh
        print_success "Docker installed"
    fi

    if ! docker compose version &> /dev/null; then
        print_warning "Docker Compose plugin not found. Installing..."
        sudo apt-get update -qq
        sudo apt-get install -y -qq docker-compose-plugin
        print_success "Docker Compose installed"
    else
        print_success "Docker Compose ready"
    fi
}

# ─────────────────────────────────────────────────────────────────
# Step 2: Install Host Nginx (if not already there)
# ─────────────────────────────────────────────────────────────────
install_nginx() {
    print_step "Checking host Nginx..."

    if command -v nginx &> /dev/null; then
        print_success "Nginx already installed"
    else
        print_warning "Nginx not found. Installing..."
        sudo apt-get update -qq
        sudo apt-get install -y -qq nginx
        sudo systemctl enable nginx
        sudo systemctl start nginx
        print_success "Nginx installed and started"
    fi
}

# ─────────────────────────────────────────────────────────────────
# Step 3: Ask for domain if not provided
# ─────────────────────────────────────────────────────────────────
ask_domain() {
    if [ -z "$DOMAIN" ]; then
        read -p "Enter your domain (e.g. skillfade.website): " DOMAIN
        if [ -z "$DOMAIN" ]; then
            print_error "Domain is required for shared VPS deployment"
            exit 1
        fi
    fi

    if [ -z "$EMAIL" ] && [ "$SKIP_SSL" = false ]; then
        read -p "Enter email for SSL certificate: " EMAIL
    fi

    print_success "Domain: $DOMAIN"
}

# ─────────────────────────────────────────────────────────────────
# Step 4: Generate .env file
# ─────────────────────────────────────────────────────────────────
setup_env() {
    print_step "Setting up environment..."

    if [ -f "$PROJECT_DIR/.env" ]; then
        print_warning ".env already exists - keeping it"
        return 0
    fi

    SECRET_KEY=$(openssl rand -hex 32)
    DB_PASSWORD=$(openssl rand -hex 16)

    cat > "$PROJECT_DIR/.env" << EOF
# Auto-generated by setup-shared-vps.sh on $(date)

# Database
DATABASE_URL=postgresql://skillfade_user:${DB_PASSWORD}@db:5432/skillfade_db
DB_PASSWORD=${DB_PASSWORD}

# Security
SECRET_KEY=${SECRET_KEY}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Email (configure later for alerts)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=

# Application
FRONTEND_URL=https://${DOMAIN}
BACKEND_URL=https://${DOMAIN}
DOMAIN=${DOMAIN}

# Alerts
ENABLE_ALERTS=true
MAX_ALERTS_PER_WEEK=1

# Environment
ENVIRONMENT=production
EOF

    chmod 600 "$PROJECT_DIR/.env"
    print_success ".env created with secure random keys"
}

# ─────────────────────────────────────────────────────────────────
# Step 5: Build and start Docker containers
# ─────────────────────────────────────────────────────────────────
start_containers() {
    print_step "Building and starting SkillFade containers..."

    cd "$PROJECT_DIR"
    mkdir -p backups

    docker compose -f "$COMPOSE_FILE" build
    docker compose -f "$COMPOSE_FILE" up -d

    print_step "Waiting for services to initialize..."
    sleep 15

    # Wait for backend health
    local retries=30
    while [ $retries -gt 0 ]; do
        if curl -s http://127.0.0.1:8100/health > /dev/null 2>&1; then
            break
        fi
        retries=$((retries - 1))
        echo -n "."
        sleep 2
    done
    echo ""

    if [ $retries -eq 0 ]; then
        print_warning "Backend still starting... (check logs with: docker compose -f docker-compose.shared.yml logs -f backend)"
    else
        print_success "Backend is healthy"
    fi

    # Verify frontend
    if curl -s http://127.0.0.1:8101 > /dev/null 2>&1; then
        print_success "Frontend is healthy"
    else
        print_warning "Frontend may still be starting..."
    fi
}

# ─────────────────────────────────────────────────────────────────
# Step 6: Configure host Nginx for SkillFade
# ─────────────────────────────────────────────────────────────────
configure_nginx() {
    print_step "Configuring Nginx for $DOMAIN..."

    # Create certbot webroot directory
    sudo mkdir -p /var/www/certbot

    # Write HTTP-only config first (needed for SSL cert)
    sudo tee /etc/nginx/sites-available/skillfade > /dev/null << 'NGINX_CONF'
# SkillFade - HTTP (auto-generated)
server {
    listen 80;
    server_name DOMAIN_PLACEHOLDER;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /api {
        proxy_pass http://127.0.0.1:8100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        proxy_pass http://127.0.0.1:8100/health;
    }

    location /docs {
        proxy_pass http://127.0.0.1:8100/docs;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8100/openapi.json;
    }

    location / {
        proxy_pass http://127.0.0.1:8101;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
NGINX_CONF

    # Replace domain placeholder
    sudo sed -i "s/DOMAIN_PLACEHOLDER/$DOMAIN/g" /etc/nginx/sites-available/skillfade

    # Enable site
    sudo ln -sf /etc/nginx/sites-available/skillfade /etc/nginx/sites-enabled/skillfade

    # Test and reload
    if sudo nginx -t 2>&1; then
        sudo systemctl reload nginx
        print_success "Nginx configured and reloaded"
    else
        print_error "Nginx config test failed!"
        sudo nginx -t
        exit 1
    fi
}

# ─────────────────────────────────────────────────────────────────
# Step 7: Get SSL certificate and upgrade to HTTPS
# ─────────────────────────────────────────────────────────────────
setup_ssl() {
    if [ "$SKIP_SSL" = true ] || [ -z "$EMAIL" ]; then
        print_warning "Skipping SSL setup"
        return 0
    fi

    print_step "Obtaining SSL certificate for $DOMAIN..."

    # Install certbot if needed
    if ! command -v certbot &> /dev/null; then
        sudo apt-get install -y -qq certbot python3-certbot-nginx
    fi

    # Get certificate using webroot
    if sudo certbot certonly --webroot -w /var/www/certbot \
        --email "$EMAIL" \
        --agree-tos \
        --no-eff-email \
        -d "$DOMAIN" 2>&1; then

        print_success "SSL certificate obtained!"

        # Now write the full HTTPS config
        sudo tee /etc/nginx/sites-available/skillfade > /dev/null << NGINX_SSL
# SkillFade - HTTPS (auto-generated)

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    http2 on;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Backend API
    location /api {
        proxy_pass http://127.0.0.1:8100;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /health {
        proxy_pass http://127.0.0.1:8100/health;
    }

    location /docs {
        proxy_pass http://127.0.0.1:8100/docs;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8100/openapi.json;
    }

    # Frontend
    location / {
        proxy_pass http://127.0.0.1:8101;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
NGINX_SSL

        sudo nginx -t && sudo systemctl reload nginx
        print_success "HTTPS enabled!"

        # Setup auto-renewal
        if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
            (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | crontab -
            print_success "SSL auto-renewal cron job added"
        fi
    else
        print_warning "SSL setup failed - site will work on HTTP"
        print_warning "Make sure DNS for $DOMAIN points to this server, then run:"
        print_warning "  sudo certbot --nginx -d $DOMAIN"
    fi
}

# ─────────────────────────────────────────────────────────────────
# Step 8: Setup backup cron
# ─────────────────────────────────────────────────────────────────
setup_backup_cron() {
    print_step "Setting up daily backup..."

    if ! crontab -l 2>/dev/null | grep -q "skillfade.*backup"; then
        (crontab -l 2>/dev/null; echo "0 2 * * * cd $PROJECT_DIR && docker exec skillfade_db pg_dump -U skillfade_user skillfade_db | gzip > $PROJECT_DIR/backups/daily_\$(date +\%Y\%m\%d).sql.gz && find $PROJECT_DIR/backups -name 'daily_*.sql.gz' -mtime +30 -delete") | crontab -
        print_success "Daily backup cron added (2 AM, 30-day retention)"
    else
        print_success "Backup cron already exists"
    fi
}

# ─────────────────────────────────────────────────────────────────
# Step 9: Setup firewall
# ─────────────────────────────────────────────────────────────────
setup_firewall() {
    print_step "Checking firewall..."

    if command -v ufw &> /dev/null; then
        sudo ufw allow 22/tcp  > /dev/null 2>&1 || true
        sudo ufw allow 80/tcp  > /dev/null 2>&1 || true
        sudo ufw allow 443/tcp > /dev/null 2>&1 || true
        print_success "Firewall rules set (22, 80, 443)"
    fi
}

# ─────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────
print_summary() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║         SkillFade Deployed Successfully!                 ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${CYAN}URL:${NC}         https://$DOMAIN"
    echo -e "  ${CYAN}Health:${NC}      https://$DOMAIN/health"
    echo -e "  ${CYAN}API Docs:${NC}    https://$DOMAIN/docs"
    echo -e "  ${CYAN}Compose:${NC}     docker-compose.shared.yml"
    echo ""
    echo -e "${YELLOW}Commands:${NC}"
    echo "  Logs:      docker compose -f $COMPOSE_FILE logs -f"
    echo "  Stop:      docker compose -f $COMPOSE_FILE down"
    echo "  Restart:   docker compose -f $COMPOSE_FILE restart"
    echo "  Update:    git pull && docker compose -f $COMPOSE_FILE up -d --build"
    echo "  Backup:    ./scripts/backup.sh"
    echo ""
    echo -e "${YELLOW}Next Steps:${NC}"
    echo "  1. Point DNS A record for $DOMAIN to this server's IP"
    echo "  2. Register your user at https://$DOMAIN"
    echo "  3. Make yourself admin:"
    echo "     docker exec skillfade_backend python grant_admin.py your@email.com"
    echo "  4. Configure SMTP in .env for email alerts (optional)"
    echo ""
}

# ─────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────
main() {
    print_banner

    # Must be root or have sudo
    if [ "$EUID" -ne 0 ] && ! sudo -n true 2>/dev/null; then
        print_warning "This script needs sudo privileges"
    fi

    ask_domain
    install_docker
    install_nginx
    setup_env
    start_containers
    configure_nginx
    setup_ssl
    setup_backup_cron
    setup_firewall
    print_summary
}

main "$@"
