// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Regenerated on every `npm run build` and `npm run dev`.
import type { BlogPostMeta } from '../../lib/blog';

export const posts: BlogPostMeta[] = [
  {
    "slug": "the-forgetting-curve-for-developers",
    "title": "The Ebbinghaus Forgetting Curve, Explained for Developers",
    "description": "The forgetting curve shows how fast unused skills fade. Here's what Ebbinghaus actually found, and how developers can use it to keep skills sharp.",
    "date": "2026-06-09",
    "tags": [
      "forgetting curve",
      "retention",
      "learning science"
    ],
    "readingTimeMinutes": 3,
    "filename": "2026-06-09-the-forgetting-curve-for-developers.md"
  }
];
